### ISSUE TITLE
오류 개선 건의

### ISSUE THREAD

**Issue by SequryS** [So-chiru/DCRefresher#10]
모든 글이 

「오류 발생
글을 받아와 파싱하려는 도중 오류가 발생 하였습니다.
d.getElementById(...) is null」

이렇게 뜨고있습니다 
이거 없으면 갤질을 할 수 없는 몸이 돼버렸습니다
바쁘시더라도 시간을 내셔서 한번만 고쳐주세요 ㅠㅠ

**Comment by So-chiru** [comment]
메이저 / 마이너 갤러리 둘러봤는데 일반적인 게시글에 해당 현상이 일어나는 경우를 재현하지 못했습니다.

짧은 시간 이내에 다수의 미리보기 / 짧은 목록 새로고침 주기로 인해 디시에서 일시 차단 처리했을 수도 있으니 해당 현상이 발생하면 잠시 기다렸다가 (5분 ~ 10분) 다시 시도해주세요.

그래도 지속적으로 해당 현상이 발생한다면 사용하는 브라우저 버전과 일어나는 갤러리 이름 등의 정보를 적어 이슈 남겨주시면 감사하겠습니다.

항상 이용해주셔서 감사합니다.
