### ISSUE TITLE
dc_refresh.js 에서 오류 발생

### ISSUE THREAD

**Issue by LSDL** [So-chiru/DCRefresher#11]
`SyntaxError: "JSON.parse: unexpected character at line 1 column 1 of the JSON data"
    <anonymous> moz-extension://85092dc4-d5d4-41cd-a5ae-43ad8a064c6b/dc_refresh.js:124`

124라인 JSON.parse 에서 오류가 발생하네요

`get_opt('blocked_dccon')
  .then(v => {
    DCCon.block.lists = JSON.parse(v)
  })
  .catch(e => {
    console.log(e)
  })`

디버깅 해보니 차단한 디시콘이 하나도 없어서, v변수값은 undefined 가 들어있습니다.

플러긴 버전: 1.0.10
파폭 버전: 77.0.1

**Comment by So-chiru** [comment]
버그 제보 감사합니다.

이 버그 수정을 마지막으로 1.0 버전대에서는 버그 수정이 없을 예정입니다. 12월 이후 출시될 2.0 버전을 기대해주세요.

<img width="759" alt="Screen Shot 2020-06-25 at 9 32 32 PM" src="https://user-images.githubusercontent.com/32066651/85720554-815c2d80-b72b-11ea-8a94-5d84e68b7be4.png">
