### ISSUE TITLE
아이피 정보 표시 기능 관련 건의

### ISSUE THREAD

**Issue by theqq123** [So-chiru/DCRefresher#14]
우선 이런 편의 프로그램을 만들어주셔서 감사합니다. 이 확장 프로그램을 쓰기 전에는 DIBE라는 놈을 쓰고 있었는데 이놈의 문제점이 갤러리 관리자가 게시물 자동갱신 기능을 쓰면 제목이 '........'로 표시된다는 점이였습니다 하지만 개발자님이 만드신 DCRefresher는 위 문제가 없어 정말 감사히 쓰고 있습니다. 

본론으로 들어가서 DIBE에 비해 DCRefresher는 표시되는 아이피 정보가 너무 적습니다. DIBE는 모든 유동 아이피의 정보가 닉네임 옆에 표시되어 갤러리 관리에 큰 도움을 주었습니다 따라서 아이피 정보를 더 추가해주셨으면 합니다.

**Comment by So-chiru** [comment]
처음엔 DIBE 같이 IP 정보를 단체, 회사, ISP 단위로 쪼개서 구현해보려고 했는데, 그렇게 하게되면 현행 방식처럼 간단히 표시할 수 없다는 점과, 시작 아이피 2자리 xxx.xxx 가 꼭 해당 기관만 사용할 것이라는 보장이 없는 점 때문에 유명한 모바일 ISP, VPN 서비스 제공사만 표기하기로 결정했었습니다.

새로 개발 중인 2.0 버전에서는 세세한 단체는 아니더라도 개인 사용자 ISP, 유명한 단체의 IP 정보를 표기할 수 있도록 구현해보겠습니다.
이외에도 다크모드, 관리자 편의 증진 기능들이 같이 추가될 예정이니 기대해주시면 감사하겠습니다.

<img width="1325" alt="Screen Shot 2020-11-22 at 11 28 27 PM" src="https://user-images.githubusercontent.com/32066651/99906426-73cac400-2d1a-11eb-936e-f76ff70ee3ae.png">


항상 사용해주셔서 감사합니다.

**Comment by So-chiru** [comment]
#78cb154 2.0에 훨씬 많은 IP 정보가 추가되었습니다.
