### ISSUE TITLE
댓글 비집고나오는문제

### ISSUE THREAD

**Issue by kimyousick** [So-chiru/DCRefresher#17]
ㅇㅇ(210.95) KT, 과학기술정보통신부, 교육청, 청운대, 국가정보자원관리원, 서울교통공사, 한국고용정보원
이런 아이피 정보들이 댓글을 뚫음
당신의 Extension Update 유용한 GALL질
빠른 Fix부탁

**Comment by So-chiru** [comment]
#21 커밋에서 수정 완료했습니다. 감사합니다!
