### ISSUE TITLE
미리보기 스크롤로 갱신 버그, 건의

### ISSUE THREAD

**Issue by pyo940216** [So-chiru/DCRefresher#19]
안녕하세요
간만에 업데이트 소식이 있었네요! 
깔끔해진 디자인이나 기능개선 한눈에 보기에도 너무나 좋아졌다는 인상입니다
업데이트 초기라 버그들이 있다 생각되는데 피드백이 되었으면 하는 바람에 이슈 등록합니다

[버그]
미리보기에서 이전글을 스크롤하여 표시하는 기능이 
연속해서 이벤트가 발생하여 바로 이전글 이동이 여러차례 발생하는 문제가 있습니다.

[건의]
관리자 패널이 너무나도 좋게 바뀌었네요
확실히 체감이 되는듯 합니다만 미리보기 패널에서 댓글이 보이는만큼
미리보기에서 댓글에 대한 삭제 차단 조치도 가능하도록 하면 어떨까 하는 생각에 건의 남깁니다

**Comment by So-chiru** [comment]
macOS 같은 마우스 이벤트가 연속적으로 발생하는 환경에서의 버그를 확인했습니다. 곧 수정하도록 하겠습니다.
댓글 삭제 기능도 추가해보도록 하겠습니다. 감사합니다!

**Comment by So-chiru** [comment]
다음 업데이트시 해당 패치가 반영될 예정입니다.
