### ISSUE TITLE
파이어폭스 설정저장 이슈 및 페이징 버그

### ISSUE THREAD

**Issue by dldhk97** [So-chiru/DCRefresher#20]
잘 사용하다가 업데이트되면서 생긴 버그가 있어 이슈 남깁니다!
OS는 윈도우 10 64비트이며, 브라우저는 파이어폭스 84.0.1 (64-비트) 입니다.

1. 설정-모듈탭은 설정이 잘 저장되나 일반 탭과 고급 탭은 설정 저장이 되지 않습니다.
 이 문제는 파이어폭스에서만 발생하는 것 같습니다.
![1](https://user-images.githubusercontent.com/20237869/103457335-afa57000-4d41-11eb-9ee6-07f8d4fbeef4.gif)

2. 게시글 목록 하단의 페이징 박스 클릭 시 페이지가 넘어가지 않습니다.
![2](https://user-images.githubusercontent.com/20237869/103457280-2d1cb080-4d41-11eb-8016-9924bcaa110c.gif)

디자인도 깔끔해지고 추가된 기능이 많아진 것 같아 좋은데 버그때문에 사용할 수가 없어 안타깝네요.
빠른 시일내에 이슈가 해결됐으면 좋겠습니다.

**Comment by So-chiru** [comment]
2번째 버그는 #21 커밋에서 수정 완료 했습니다. 1번째 오류는 수정해보도록 하겠습니다. 감사합니다!

**Comment by So-chiru** [comment]
about:addons에서 설정을 진행할 때 해당 증상이 발생하는 것을 확인 했습니다. 오류가 해결될 때까지 디시인사이드 페이지에서 확장 프로그램 아이콘을 클릭하여 설정을 진행해주세요.
