### ISSUE TITLE
검색 결과가 최신 글 목록으로 덮어씌여집니다.

### ISSUE THREAD

**Issue by pinkswall** [So-chiru/DCRefresher#24]
![bf](https://user-images.githubusercontent.com/29687306/103459530-07bf8080-4d08-11eb-9e2b-f859c6b0c3c8.png)
덮어 씌여지기 이전

![after](https://user-images.githubusercontent.com/29687306/103459589-7e5c7e00-4d08-11eb-847a-cee9ad00e928.png)
덮어 씌여진 이후 (검색 결과가 없을 시 레이아웃이 깨짐)  

검색 결과가 1-2초 이후에 최신 글 목록으로 덮어씌여집니다.

**Comment by So-chiru** [comment]
수정 완료 했습니다. 제보 감사드립니다.
