### ISSUE TITLE
게시글 검색할땜다 새로고침으로 인한 깨짐 현상

### ISSUE THREAD

**Issue by xotkek925** [So-chiru/DCRefresher#25]
게시글 검색할때 새로고침때문에 화면이 깨지거나 새로운 글로 넘어가는 현상이 있음
검색기능 이용할때는 새로고침이 안되면 좋을거 같은데 가능하시면 관련 기능도 추가해주셨으면 좋겠습니다.

**Comment by So-chiru** [comment]
새로고침 시 다른 검색 결과가 나오는 버그는 8d582e578 에서 수정 완료 했습니다. 스토어 업데이트까지는 조금 걸릴 듯 합니다.

검색 시에는 새로고침 방지 옵션은 버그가 계속 발생할 경우 한번 넣어보도록 하겠습니다. 감사합니다.
