### ISSUE TITLE
미리 보기 날짜 오류 및 건의

### ISSUE THREAD

**Issue by laxotor** [So-chiru/DCRefresher#26]
![Screenshot_2021-01-03 국내야구 갤러리(1)](https://user-images.githubusercontent.com/43947445/103471188-87108b00-4dc0-11eb-9c60-3612ae8d68e7.png)

미리 보기에서 날짜 정보가 제대로 안 뜹니다.

그리고 많이 겹치는 IP는 압도적으로 뜨는데 개선 해주셨으면 좋겠습니다.

**Comment by So-chiru** [comment]
수정 완료했습니다. 다음 업데이트 시 함께 반영하도록 하겠습니다. 감사합니다!

**Comment by laxotor** [comment]
![Screenshot_2021-01-04 국내야구 갤러리](https://user-images.githubusercontent.com/43947445/103524896-a9d69880-4ec1-11eb-9ede-78aaebdb26ba.png)

2.0.4 업데이트 이후
게시물 날짜는 정상적으로 표시되지만, 댓글 날짜는 아직 정상적으로 뜨지 않습니다.
