### ISSUE TITLE
현재 보고 있는 글 indicator가 글 목록 fetch시에 사라지는 이슈

### ISSUE THREAD

**Issue by loveliveall** [So-chiru/DCRefresher#27]
![image](https://user-images.githubusercontent.com/50051759/103473941-6dcc0680-4de1-11eb-9d28-f8d02b65d98a.png)

글을 좌클릭해서 읽게 되면 글 목록에 위와 같은 식으로 현재 보고 있는 글이 표시되는데

해당 표시가 글 목록이 새로고침되면서 사라지는 이슈가 있습니다.

사용상에 불편함을 유발하는 건 아니긴 한데, 그냥 보고 있자니 불-편해서 이슈 라이징합니다.

**Comment by So-chiru** [comment]
불-편은 못참죠

**Comment by So-chiru** [comment]
다음 업데이트시 반영될 예정입니다. 감사합니다!
