### ISSUE TITLE
다크 모드 배경 블러 버그

### ISSUE THREAD

**Issue by laxotor** [So-chiru/DCRefresher#28]
![Screenshot_2021-01-03 국내야구 갤러리](https://user-images.githubusercontent.com/43947445/103479607-42addb00-4e12-11eb-9b7b-4d3b6d759aa0.png)

다크 모드 상태일 때 배경 블러 옵션이 적용되지 않습니다.

**Comment by So-chiru** [comment]
Firefox는 배경 블러 처리에 사용하는 backdrop-filter를 지원하나 기본적으로 비활성화되어 있는 상태입니다.
이를 활성화하기 위해서는 `about:config`로 이동하여
```
gfx.webrender.all
layout.css.backdrop-filter.enabled
```

두 가지 항목을 true로 바꿔주신 후 재시작하시기 바랍니다.

**Comment by laxotor** [comment]
헉, 블러 옵션이 진짜 블러 효과 적용되는 거였네요
라이트 모드에선 배경 투명도만 바뀌어서 투명도만 추가하는 줄 알았습니다..

그러면 혹시 다크 모드에서 블러 효과를 비활성화했을 때
라이트 모드처럼 배경 투명도를 없애면 어떨까 싶습니다.
