### ISSUE TITLE
문의

### ISSUE THREAD

**Issue by pyo940216** [So-chiru/DCRefresher#29]
안녕하세요.
DCRefresher 이용중 여쭈고싶은 내용이 있어 문의 남깁니다.

1. 최근 업데이트된 2.0버전에서 모듈이라는 항목이 추가된것을 확인하였습니다.
개인적으로는 오픈소스로서 기여를 받는것을 고려하고 만드신 항목이라 생각이 되는데, DCRefresher에 모듈 제작으로 기여, 혹은 기능 추가에 참여하는것이 가능할까요.

2. safari 브라우저도 확장 프로그램을 지원하기 시작하였습니다만, 혹시 DCRefresher를 추가하실 계획이나 추가해주실 수 있는지요 (DCRefresher때문에 갤질편하게하려고 사파리말고 크롬쓰는중... )

답변 기다리겠습니다

**Comment by So-chiru** [comment]
1. 모듈 시스템은 확장 가능하게 구현 해둬서 언제든지 모듈을 개발하여 Pull Request 주시면 적용시켜드릴 수 있습니다. 나중에 모듈 개발 방법을 따로 README에 적어두겠습니다.

2. `safari-web-extension-converter`로 가능하면 따로 빌드된 바이너리 파일을 Release에 추가해서 올릴 수는 있겠지만 정식 스토어 등록은 개발자 인증서 때문에 매년 99$ 내야하는 불편함이 있어서 어려울 듯 싶습니다.

**Comment by pyo940216** [comment]
언제나 친절한 답변 감사합니다.
README관련해서는 방금 확인하였습니다. 
조금씩 기여 할 수 있었으면 좋겠네요.
