### ISSUE TITLE
부가 기능 제안

### ISSUE THREAD

**Issue by loveliveall** [So-chiru/DCRefresher#3]
1. 유동닉 IP 대역 중 유명한 IP 대역은 글 목록에서 별도 표기 (ex. `ㅇㅇ(39.7) [KT통피]` 등)
2. 고닉 및 반고닉 아이디를 글 목록에서 닉 옆에 ()로 표시 (현재 글 미리보기에서 글 작성자랑 댓글 작성자의 경우는 해당 기능 적용된 상태) (ex. `으유카와(rupok)`)
3. 이용자 메모 기능...도 아예 같이 있으면 좋겠다고 생각은 하는데 UX를 어떻게 구성해야 할지는 직관적으로 딱 떠오르는게 없네요. 공앱 이용자 메모한거 PC에서 볼 수 있나..?

**Comment by So-chiru** [comment]
1번은 현재 구현했고
2번은 닉네임 칸을 너무 많이 잡아 먹어서 게시글 페이지에서만 볼 수 있도록 할 수 있을거 같아요
3번은 한번 해 보겠습니다 👍

**Comment by loveliveall** [comment]
개발력 ㅎㄷㄷ 하시군요
