### ISSUE TITLE
우클릭 말고 마우스를 올려서 미리보기 창이 뜨게 하는 기능도 추가하면 좋겠슴다

### ISSUE THREAD

**Issue by gam-b1t** [So-chiru/DCRefresher#30]
그 외에는 디자인이랑 편리성이 디시 확장 프로그램중에서 가장 뛰어남
만들어줘서 고마워요

**Comment by So-chiru** [comment]
마우스 올려서 미리보기 기능은 현재 개발 중이고 2.1 버전에 함께 추가될 예정입니다. 감사합니다!
