### ISSUE TITLE
파이어폭스 다크 모드 자동 새로고침 시 읽은 글 깜박거림

### ISSUE THREAD

**Issue by laxotor** [So-chiru/DCRefresher#31]
![95](https://user-images.githubusercontent.com/43947445/103792424-f9b28c80-5086-11eb-8a4c-ce725942fc01.gif)

다크 모드 상태에서

자동 새로고침 될 때마다 읽은 글들이 저렇게 깜박거립니다.

**Comment by So-chiru** [comment]
파이어폭스 링크 색상 repaint가 느리게 일어나는 문제인듯 싶네요.
[https://bugzilla.mozilla.org/show_bug.cgi?id=484928](https://bugzilla.mozilla.org/show_bug.cgi?id=484928)

확장 프로그램 선에서는 해결이 불가능하나, 차선책으로 방문 링크 색상 지정 비활성화 옵션을 사용할 수 있도록 추가해드렸으니 추후에 업데이트가 이루어지면 해당 옵션을 이용해주세요.
