### ISSUE TITLE
파이어폭스 시크릿모드 미리보기 추천/비추천 버그 제보

### ISSUE THREAD

**Issue by dldhk97** [So-chiru/DCRefresher#32]
버그 픽스가 꾸준히 되어 잘 사용하고 있습니다.
사용하던 중 불편한점이 있어 제보합니다.

![파이어폭스 무반응](https://user-images.githubusercontent.com/20237869/103925460-ebce3b80-515a-11eb-9b93-db18c145052c.gif)

미리보기 창에서 크롬은 시크릿모드일때도 추천/비추천이 잘되는데 파이어폭스는 추천/비추천 기능이 동작하지 않습니다.
시크릿모드가 아니면 잘 동작합니다.

시크릿모드를 주로 쓰는데, 미리보기로 추천이 안돼서 미리보기를 닫고 게시물을 열람해야하는 불편함이 있습니다.

감사합니다.

**Comment by So-chiru** [comment]
디시는 추천 요청을 보낼 때 HTTP Referer 헤더도 같이 확인하는데, Firefox 59부터 생긴 Private Browsing 모드에서 Referer 헤더의 path를 잘라버리는 보안 기능 (링크 탄 사이트에서 이전에 방문한 사이트 확인 가능 문제) 때문에 오류가 발생합니다. 크롬도 동일하게 작동하나 크롬은 확장 프로그램 context와 페이지 context가 동일한 선상에서 돌아가기 때문에 same-site Origin이 적용되어 문제가 발생하지 않습니다.

[https://blog.mozilla.org/security/2018/01/31/preventing-data-leaks-by-stripping-path-information-in-http-referrers/](https://blog.mozilla.org/security/2018/01/31/preventing-data-leaks-by-stripping-path-information-in-http-referrers/)

결론은 이 문제 역시 확장 프로그램 선에서는 해결할 수 없는 문제이나, 사생활 문제를 감수하고서라도 사용하기를 원하신다면 about:config로 가셔서 `network.http.referer.defaultPolicy.pbmode` 값을 일반 모드와 동일한 `3` (no-referrer-when-downgrade) 으로 맞춰주시기 바랍니다.
