### ISSUE TITLE
새로고침과 프리뷰가 연동되지 않는 문제

### ISSUE THREAD

**Issue by Seo-Rii** [So-chiru/DCRefresher#37]
프리뷰 모듈에서 스크롤을 사용해서 다음/이전 게시글을 보는 기능이 새로고침 모듈로 추가된 게시글에는 적용되지 않습니다.

**Comment by So-chiru** [comment]
버전 2.1.1, Chrome 87.0.4280.141 기준으로는 정상 작동하는 데 사용하시는 확장 프로그램 버전과 브라우저 버전을 알려주시면 감사하겠습니다!

**Comment by Seo-Rii** [comment]
다시 테스트해보니 새로고침과 관련된 문제가 아니라 스크롤이 가끔씩 작동하지 않는 문제같습니다.
확장프로그램은 최신, 브라우저는 MS Edge DEV(Chromium) 89.0.752.1입니다.
