### ISSUE TITLE
branch 관련 issue

### ISSUE THREAD

**Issue by Seo-Rii** [So-chiru/DCRefresher#46]
branch를 만들어서 작업하고 있는데, 리뷰어 제한때문에 push가 안되네요 ㅋㅋㅋ
리뷰 조건을 main 브랜치에만 적용해주실수 있나요?

**Comment by So-chiru** [comment]
풀었습니다! 한번 푸시 해봐주세요

**Comment by Seo-Rii** [comment]
잘 되네요. 감사합니다!
