### ISSUE TITLE
기능검토를 위한 브랜치 추가요청 

### ISSUE THREAD

**Issue by pyo940216** [So-chiru/DCRefresher#49]
안녕하세요. 
최근 모듈에 기능을 추가하고자 개발을 진행해 왔습니다만,
현재 어느정도 시안이 작성되어 해당 기능 적용이 가능한지 검토를 부탁드리고싶습니다.
다만 현재 마스터 이외의 기능 검토용으로 풀 리퀘스트 할만한 브랜치가 없어
추가를 부탁드리고 싶습니다만 가능할까요?

**Comment by So-chiru** [comment]
Collaborator 초대 보내드렸습니다. 승인하시고 새로 브랜치 만드셔서 Pull Request 하시면 될 것 같습니다.

**Comment by pyo940216** [comment]
stealth-mod 브랜치로 추가하였습니다.
기능내용으로서는 후방주의, 갤러리 이미지 비디오 숨김으로서 

- 갤러리 메인 페이지 이미지 숨김, 레이아웃 수정
- 미리보기창 이미지 숨김, 이미지가 존재할경우 일시 해제 버튼 표시(좌측하단 관리자 컨트롤 패널 옆) 
- 댓글디씨콘 마우스오버시 일시표시
- 댓글돌이 삭제
- 글에 이미지 존재할 경우 스텔스모드 일시 해제 버튼 표시
입니다.

현재 시안수준으로 만들어져 소스 수정등이 필요합니다만,
위 내용들로 개발시 적용이 가능할지 기능 확인 및 검토 요청차 이슈 남깁니다.

**Comment by So-chiru** [comment]
Pull Request 올려주세요

**Comment by pyo940216** [comment]
Pull Request 등록하였습니다. 확인 부탁드립니다!

**Comment by So-chiru** [comment]
#50
