### ISSUE TITLE
조작기 모듈 관련 문의 남깁니다.

### ISSUE THREAD

**Issue by pyo940216** [So-chiru/DCRefresher#55]
현재 모듈에 조회수 관련 조작기 기능이 추가되어있습니다. 
사이트 공격이나 악용사례로 생각되는데 
정상적인 추가 내용 맞는지 확인 부탁드립니다.

**Comment by So-chiru** [comment]
소스 모듈에서는 업로드된 부분이 없네요. release에 추가된 사항인가요?

**Comment by pyo940216** [comment]
지금 소스를 확인 할 수 있는 상황이 아니라.. 
현재 2.1.1 버전 모듈탭에서 확인됩니다.

**Comment by So-chiru** [comment]
다시 컴파일해서 올려보겠습니다.

**Comment by So-chiru** [comment]
써드파티 모듈 기능이 추가될 때 fetch API를 이용하여 정상적이지 않은 요청을 보낼 때 (주작기, http 요청 도배) 이를 확장 프로그램 단에서 막아보려고 테스트 케이스로 넣어둔 모듈이 같이 빌드된 모양입니다.

2.2 버전을 올려둔 상태고 이 버전에서는 모듈이 제거된 후에 올라갈 예정입니다. 불편을 드려 죄송합니다.
