### ISSUE TITLE
댓글 관련 버그 

### ISSUE THREAD

**Issue by pyo940216** [So-chiru/DCRefresher#58]
안녕하세요.
개발 중 미리보기 댓글창 관련하여 버그라 생각되는 동작을 발견하여 이슈 등록합니다.

미리보기창 표시 중 디씨콘에 마우스를 대는 경우(마우스오버)
약간의 레이아웃 망가짐이 발생합니다

원인으로서는
1. 최초 댓글 표시시 refresher-comment-content에 곧바로 written_dccon 클래스를 가진 자식태그로서 디시콘이 표시 
2. 마우스오버시 comment_dccon 클래스를 가진 요소로 갱신
3. 최초 디씨콘 표시시의 높이(100px)과 마우스 오버시 갱신된 높이(103px)가 달라 레이아웃 망가짐으로 보임

현재 이전 검토차 연락드린 스텔스모드 관련하여 작업중 함께 수정을 고려하였으나
최초 표시시와 마우스를 댔을 때의 어느쪽이 사양에 맞는지 확실치않아 사양 확인차 이슈남깁니다.

최초표시시의 사양이 맞는 경우 
디씨콘이 표시되는 video, img태그 부모태그에 스타일을 적용하는 일이 있으리라 생각되는 만큼
별도의 refresher-comment-content 클래스 속성과 구분되는 디씨콘 관련의 태그나 클래스 속성 추가를 건의드립니다.

**Comment by So-chiru** [comment]
@pyo940216 이제 refresher-comment-content와 별개로 dccon 클래스를 표시합니다.

**Comment by pyo940216** [comment]
#62 에서 해당 이슈 수정
