### ISSUE TITLE
URL 복사 기능 제안

### ISSUE THREAD

**Issue by pakubetchi** [So-chiru/DCRefresher#6]
미리보기 창에서 그 글의 URL을 클립보드에 복사할 수 있는 버튼이 있으면 좋을 것 같습니다. 불판을 자주 이용하는데 이 기능이 있다면 제보 댓글을 다는 과정이 한결 편해질 것 같아요!

사용자의 동선 예시는 아래와 같습니다.
> 미리보기 창 열기 -> `urlCopyButton` 클릭 -> PC의 클립보드에 URL 복사

URL은 디시인사이드 공유하기 기능에서 제공하는 URL을 사용합니다. 양식은 아래와 같습니다.
> 일반 갤러리: `https://gall.dcinside.com/갤러리 고유 ID/글 번호`
> 마이너 갤러리: `https://gall.dcinside.com/m/갤러리 고유 ID/글 번호`

**Comment by So-chiru** [comment]
✅ 2.0에서 구현 완료
