### ISSUE TITLE
기능 추가 건의 드립니다.

### ISSUE THREAD

**Issue by YaPurO** [So-chiru/DCRefresher#60]
안녕하세요. 우선 훌륭한 확장 앱 만들어 주셔서 정말 감사드립니다.
기존에 사용하던 다른 확장 앱의 기능 중 유용하게 사용하던 기능이 있어 건의 드립니다.

1. 불필요한 요소를 지울 수 있고,
1. 남는 공간으로 글 간격을 넓힐 수 있는 기능.

우선 아래 이미지가 현재 DC리스레셔 사용 시의 화면이구요.

![스크린샷(1154)](https://user-images.githubusercontent.com/13184195/104843803-e073d080-590f-11eb-9814-6f78d7e60da5.png)

아래 이미지는 기존에 사용중이던 확장 앱 사용 시의 화면입니다.

![스크린샷(1155)](https://user-images.githubusercontent.com/13184195/104843807-e23d9400-590f-11eb-854e-64c5f4180d44.png)

디씨를 켰을때 화면에 나타나는 요소들을 확장 앱 단에서 제어할 수 있는 기능입니다.
원본 페이지가 워낙 상하좌우로 묻어있는게 많아서 이 기능이 갤질할때 되게 다가오더라구요.

검토 부탁드리겠습니다. 감사합니다!

**Comment by So-chiru** [comment]
레이아웃 수정 모듈에 옵션으로 넣어 구현해보도록 하겠습니다. 감사합니다!
