### ISSUE TITLE
2.3.0 업데이트 이후 미리보기에서 글, 댓글 작성자가 표시되지 않는 오류

### ISSUE THREAD

**Issue by YaPurO** [So-chiru/DCRefresher#63]
우선 빠른 기능 추가 반영 감사드립니다.

다름이 아니고 업데이트 이후 미리보기 화면에서 글과 댓글 작성자 닉네임이 표시되지 않는 오류가 있습니다.

1. 일반 - 폰트, 레이아웃 수정 관련 메뉴
1. 모듈 - 광고, 컨텐츠, 폰트, 레이아웃 모듈

미리보기 본 기능을 제외한 상기한 레이아웃에 영향을 줄 수 있는 옵션들을 모두 비활성화해봐도 표시가 안 되네요.

## 2.2.0
![스크린샷(1156)](https://user-images.githubusercontent.com/13184195/105004821-cfde6a00-5a77-11eb-888b-010af81c2355.png)

## 2.3.0 (2.2.0과 설정값 동일)
![스크린샷(1157)](https://user-images.githubusercontent.com/13184195/105004819-cead3d00-5a77-11eb-88ea-374f293185e9.png)

**Comment by So-chiru** [comment]
사용하시는 브라우저가 어떻게 되시나요?

**Comment by So-chiru** [comment]
버그 재현이 불가능해서 브라우저 F12 누르시고 나오는 콘솔창을 캡쳐해서 올려주시면 감사하겠습니다

**Comment by YaPurO** [comment]
윈도우10 환경 웨일 브라우저 2.8.108.15 사용중입니다.

![스크린샷(1158)](https://user-images.githubusercontent.com/13184195/105017804-9150ab80-5a87-11eb-8da7-03dd43dda8dd.png)
![스크린샷(1159)](https://user-images.githubusercontent.com/13184195/105017801-901f7e80-5a87-11eb-855c-c0521ddbe0e6.png)

**Comment by So-chiru** [comment]
`.replaceAll` API가 Chrome 85 미만에서는 지원하지 않아 발생하는 오류였습니다. (웨일은 Chrome 83) 2.3.1버전에서 수정되어 올라갈 예정입니다.
