### ISSUE TITLE
기능 건의

### ISSUE THREAD

**Issue by BonFire145** [So-chiru/DCRefresher#64]
폰트 사이즈 변경, 미리보기에서 댓글달기 기능좀

**Comment by Seo-Rii** [comment]
미리보기 댓글 관련 기능은 현재 개발중이며 추천하지는 않지만 고급 탭에서 활성화시킬수 있습니다. (단, 현재 로직이 완전히 적용되지 않아 차단을 당할수도 있으며 이는 본인 책임입니다.)
자세한 내용은 #53 을 참고하세요.
