### ISSUE TITLE
[중요] IP 차단

### ISSUE THREAD

**Issue by Seo-Rii** [So-chiru/DCRefresher#70]
확장프로그램을 사용할시 댓글 기능을 사용하지 않아도 몇 시간이 지나면 디시 전체에서 IP차단을 먹는것 같습니다.
(게시글 접속시 아무것도, 심지어 UI도 로드되지 않음)
현재 모든 옵션을 기본으로 두고 사용하고 있습니다.

**Comment by So-chiru** [comment]
새로고침 모듈 주기가 이상한 것 같던데 그 문제일 수도 있겠습니다.

**Comment by Seo-Rii** [comment]
아니면 새로고침을 할 시 타이밍을 랜덤으로 하는것은 어떤가요? (예: 1000-1100ms 사이 랜덤)

**Comment by So-chiru** [comment]
주기 자체는 문제 없는데 너무 빠르게 많이 요청하면 일시적으로 10분 차단 먹는거라 요청을 너무 많이 보내는 경우 모듈 단에서 안보내게하는 편이 나을 것 같습니다
