### ISSUE TITLE
2.5 업데이트 이후 미리보기 기능이 아예 작동하지 않음

### ISSUE THREAD

**Issue by Seo-Rii** [So-chiru/DCRefresher#74]
새로 추가된 메모 기능이 문제를 일으키는 것 같습니다.

지속적으로 아래 오류가 발생하며 미리보기 기능이 아예 작동하지 않습니다.
CANNOT READ PROPERTY 'NICK@' OF UNDEFINED

**Comment by So-chiru** [comment]
크롬 브라우저 인가요?

**Comment by Seo-Rii** [comment]
크로뮴 엣지(90)입니다

**Comment by Seo-Rii** [comment]
또한, 에러 핸들링이 최초 한번만 작동하고 이후에는 작동하지 않습니다.
![image](https://user-images.githubusercontent.com/48939845/107528357-151c3480-6bfd-11eb-96fe-f6e111e4a8e3.png)

**Comment by So-chiru** [comment]
파이어폭스는 2.5.1 핫픽스 올려뒀는데 크롬은 심사가 느려서 언제 적용될지는 모르겠네요.

**Comment by Seo-Rii** [comment]
아 2.5.1 수정사항이 파이어폭스 말고도 크롬에도 적용되는건줄 몰랐네요;;
이슈 닫겠습니다.
