### ISSUE TITLE
유식이가 다크모드가 만들고 나서 확장 앱 내 기능과 꼬인거같습니다.

### ISSUE THREAD

**Issue by YaPurO** [So-chiru/DCRefresher#77]
다른 부분은 상관없는데 글쓰기 할 때 에디터 배경이 까맣게 되서 글을 쓸 수가 없어졌어요...

디씨 공식 다크모드와 병행해서 사용하면 에디터에서 글 색깔까지 바꿔줘서 보이기는 하는데
이런식으로 쓰면 글 목록 색상은 다 깨지고 미리보기 글자 색이 미리보기 창화면과 비슷해져서 보기 힘들어집니다.

![화면 캡처 2021-02-18 205844](https://user-images.githubusercontent.com/13184195/108354013-31872500-722c-11eb-9d66-6284c3f43b30.png)
![화면 캡처 2021-02-18 205806](https://user-images.githubusercontent.com/13184195/108354017-32b85200-722c-11eb-86de-a9cea2f7f6f7.png)

**Comment by So-chiru** [comment]
실시간으로 업뎃 중이라 다 끝나면 그때 적용하도록 하겠습니다
