### ISSUE TITLE
크로미엄 90 기반 브라우저서 사용시 미리보기 및 레이아웃 관련 기능 오작동

### ISSUE THREAD

**Issue by Gnbrkm41** [So-chiru/DCRefresher#78]
Microsoft Edge Dev Version 90.0.796.0 (Official build) dev (64-bit) 및 비슷한 버전의 Chrome Dev에서 프로그램 설치 시 우클릭 미리보기 및 컴팩트 모드 등이 정상적으로 적용되지 않습니다.
![화면 캡처 2021-02-19 025138](https://user-images.githubusercontent.com/42944058/108399873-f1d93100-725d-11eb-944b-99d89ccc029a.png)

89버전에선 문제가 발생하지 않던 것으로 기억하나 문제가 90버전 업그레이드와 동시에 발생했는지는 자세히 모르겠습니다. Chrome 기본 설치 설정에서 별다른 확장 프로그램 (애드블록 포함) 없이 시도 시에도 동일한 문제가 발생합니다.

다크모드 추가 이전부터 발생한 것으로 기억합니다.

**Comment by So-chiru** [comment]
F12 눌러서 나오는 개발자 콘솔에 표시되는 오류가 있나요? Chrome Dev 90.0.4421.5에서 시도 해봤는데 별 다른 문제는 없었습니다

**Comment by So-chiru** [comment]
엣지에서는 크롬과 다르게 페이지 CSS가 확장 프로그램 CSS 보다 우선되어 버리네요. 페이지 reset.css를 확장 프로그램에서 구현을 해야할 듯 싶습니다.

**Comment by So-chiru** [comment]
Edge Canary에서 사용하는 Chromium 버전 Chrome/90.0.4414.0 에서는 injected stylesheet 보다 page css가 우선되는 버그가 있어 해당 오류가 발생하는데 그 다음 버전인 Chrome/90.0.4415.0 에서는 문제가 해결이 됐습니다. 엣지에서 Chromium 버전을 업데이트할 때까지 기다리셔야 할듯합니다.

**Comment by Gnbrkm41** [comment]
감사합니다!
