### ISSUE TITLE
레이아웃 관련 기능이 본문 내에서도 적용이 가능한지요?

### ISSUE THREAD

**Issue by Gnbrkm41** [So-chiru/DCRefresher#79]
#78 문제 발생 이전에도 링크를 클릭해서 본문을 들어갈 시 레이아웃 관련 기능이 하나도 작동하지 않았던 것으로 기억하는데 (좌우로 공백 남음 등등), 이것이 버그로 인한 것인지 아니면 아직 구현되지 않은 것인지 궁금합니다.

**Comment by So-chiru** [comment]
원래 적용되지 않았던 부분이 맞습니다. 본문 내에서도 레이아웃 기능이 작동하도록 하겠습니다.
