### ISSUE TITLE
미리보기 기능 개편 건의

### ISSUE THREAD

**Issue by Final-Lecture** [So-chiru/DCRefresher#8]
개발자님이 개발하신 디시 확장 프로그램 매우 유용하게 사용하고 있습니다. 개발자님의 노고에 감사인사 드립니다.

현재 확장 프로그램의 미리보기는 제목에 대고 우클릭을 해야 미리보기가 가능합니다. 적은 양의 글을 볼때는 많이 불편하지는 않지만, 다량의 글을 볼 때 손의 피로도가 많이 높아집니다.

그래서 건의드리건대, 혹시 마우스 커서를 갖다대는 것 만으로도 미리보기 기능을 사용할 수 있도록 개편해 주시는게 어떨지, 제안 드립니다.

감사합니다.

**Comment by So-chiru** [comment]
현재 최신 버전인 v1.~~ 은 소스가 개판이라 건들 수 없어서 구현이 어려울 듯 하고

개발 중인 v2에서는 글을 미리 보는 방식을 차단형 팝업식과 비 차단형 팝업식으로 나눠 한번 구현해보도록 하겠습니다.
사용해주셔서 감사합니다.
