### ISSUE TITLE
파이어폭스 애드온 페이지에서 DCRefresher가 사라졌습니다.

### ISSUE THREAD

**Issue by dldhk97** [So-chiru/DCRefresher#82]
잘 사용하고 있었는데, 새 PC에서 설치하려니까 안보이네요.
확인해주시면 좋을거같습니다!

https://addons.mozilla.org/ko/firefox/search/?q=DCRefresher

항상 감사합니다.

**Comment by So-chiru** [comment]
https://github.com/So-chiru/DCRefresher/discussions/80#discussioncomment-548904

설치는 직접 패키지를 빌드하시거나 https://github.com/So-chiru/DCRefresher/releases 가셔서 최신 버전의 빌드된 zip 파일을 받으신 후에 압축을 푸시고,
chrome://extensions 에서 `압축해제된 확장 프로그램을 로드합니다.` 버튼을 눌러 설치할 수 있습니다.
