### ISSUE TITLE
어플에 사진차단 기능이 생겼다는데 ...

### ISSUE THREAD

**Issue by sosoeun** [So-chiru/DCRefresher#84]
안녕하세요 재밌게 잘사용하고 있답니다.

혹시 사진차단기능을 추가하실 생각은 없으신가요

개발종료했다는 사실은 알지만..

사진 어그로로 고통받고 있어서 혹시나 하는 마음에 물어봅니다..

**Comment by So-chiru** [comment]
요즘 개인적으로도 바쁘고 디시는 아예 활동하지도 않아서 새로운 기능 추가는 어려울 것 같습니다..
