### ISSUE TITLE
공지로 등록된글을 공지로 등록되었다고 인식하지못함

### ISSUE THREAD

**Issue by emptycan1010** [So-chiru/DCRefresher#85]
이미 공지로 등록된글을 내리려고 보아도 공지 등록해제버튼이아닌 공지로 등록버튼만 존재하는 버그가 있는거같아요.

**Comment by green1052** [comment]
https://github.com/So-chiru/DCRefresher#%EC%97%85%EB%8D%B0%EC%9D%B4%ED%8A%B8

개발 중단 됐어요
