### ISSUE TITLE
기능 추가 건의

### ISSUE THREAD

**Issue by pyo940216** [So-chiru/DCRefresher#9]
안녕하세요 개발하신 크롬익스텐션 언제나 잘 사용하고 있습니다.
다름이 아니라 마갤 관리에  불편함을 느껴 DCRefresher의 기능 추가로서 조금 더 편하게 사용이 가능하지 않을까하여 추가 기능을 건의드립니다.

[미리보기]
-갤러리 관리 권한이 있는 경우(글 삭제버튼 표시시) 미리보기 맨위쪽에서도 개추/비추/삭제버튼 표시

제목만 보거나 내용을 대략적으로도 삭제해야하는 글의경우 
그러한 글들을 일일히 내리느라 대응시간이 늦어지네요 .
특히나 혐짤같은 경우 그러한 사진들을 무조건 내리면서 다보고 삭제를 해야하니 
이러한 부분이 추가가 되면 상당히 도움이 될듯합니다.

[갤러리 메인]
-삭제/차단/개념글 해제 버튼의 플로팅

갤러리 관리시 높은 확률로 최상단의 글들에 대해 삭제하거나 차단하거나 개념글을 해제합니다.
이 버튼이 최하단에 있으니 맨윗글을 체크하고 맨아래로 내려서 버튼을 누르려니 조작이 매우 불편해지네요.
전체글, 개념글 아래에 나타나는 삭제/차단/개념글해제 버튼이 화면일정부분에서 
스크롤을 내리고 올리더라도 따라다니면 정말 편할것 같다고 생각했습니다.

사용자 환경을 개선하는건 디씨측에서 해야할 일이라 생각합니다만 절대 해줄일이없으니...
위 기능 추가를 제안드려봅니다.

감사합니다.

**Comment by So-chiru** [comment]
우선 아이디어 제안 감사합니다!

글 관리 버튼이 개추/비추 버튼 옆에 있어서 글 삭제 시 어려움을 겪고 있는 점은 이미 인지하고 있던지라 현재 작업 중인 2.0 버전에서 적용할 디자인을 구상은 해 둔 상태입니다.

해당 문제가 수정될 2.0 버전에서는 마이너 갤러리 관리 툴바를 창 안에 포함하는 것이 아니라 미리 보기 창 밑에 관리 창을 만들어 그 창 안에서 차단 / 삭제 / 고정 등과 같은 게시글 관리 작업을 할 수 있도록 할 예정입니다.

개인적인 얘기지만, 현재 수능 준비하느라 어느 정도 개발에 차질이 있을 듯합니다.. 수능이 끝난 후에야 다시 확장 프로그램 업데이트가 가능할 듯하니 그때까지는 업데이트가 힘들 수 있다는 점 양해 부탁드립니다.

항상 이용해주셔서 감사합니다.

**Comment by pyo940216** [comment]
정성들여 답변해주셔서 감사합니다. 
학생분이셨나요? 
학생분이시면 그 능력에, 아니시더라도 배우고자 하시는 그 열정에 
감탄하게 되네요.

좋은 프로그램 만들어주셔서 너무나 편하게 사용하고 있습니다.
더 좋게 만들어주실 2.0버전도 기대하고 있겠습니다. 
좋은 하루되세요.
